Add sign_in_path as a helper method and fix some failing tests due to layout changes
There are two tests failing related to attempt to post / edit articles when not
signed in. It seems like an error with the related code, but we cannot test it
entirely. I've already got into the same error while testing the app.:

ArgumentError: wrong number of arguments (2 for 1)
    app/services/university_web/user.rb:26:in `find'
    app/services/university_web/user.rb:14:in `find_by_github'
    app/controllers/sessions_controller.rb:31:in `check_permissions'